### ISSUE TITLE
[Feature Request] Support for iOS?

### ISSUE THREAD

**Issue by whitehat007** [Balancingrock/SwifterLog#2]
Is there any way to implement the main logging functionality for iOS? I'd imagine that instead of logging to system files, we would create a new log file within the app sandbox. I would be happy to help but I don't know much about working with iOS file systems.

**Comment by Balancingrock** [comment]
I have not tried to compile this for iOS, it should not be too much trouble though...
If you can wait, I'll have a look tomorrow.

**Comment by whitehat007** [comment]
Yup, no rush :)

**Comment by Balancingrock** [comment]
Well, it turns out there are a few snags. Most of these have to do with the way libraries are handled.
Xcode 11 should support the SPM for iOS targets as well. And while I have not checked lately, I believe that the release of Xcode 11 is around the corner. Hence to me it does not make sense to spend time "pre-inventing the wheel" when official support is on its way.

When Xcode 11 is out, we will take a very serious look to support iOS. Not only for SwifterLog, but for other packages as well.

**Comment by whitehat007** [comment]
Any updates on this?

**Comment by Balancingrock** [comment]
We are currently working to get a major release ready for Swiftfire. After that release we will take a break from adding new features to Swiftfire and concentrate on "minor" stuff like adding more platforms to our lineup of packages.

So it's coming, but not yet at the top of the list.

**Comment by whitehat007** [comment]
I copied `SwifterLog.swift` directly into my project and commented out anything related to ASL. So far, it seems to work well.

**Comment by Balancingrock** [comment]
That should work for the older versions where SwifterLog was still one file. Be sure to check for any bugs that were fixed in later version in the history of the readme.

**Comment by whitehat007** [comment]
Is there any change to the official support status for iOS? I greatly enjoy the power and versatility of this package and I'd like to be able to keep it up-to-date rather than having to rely on the old version that I hacked together.

**Comment by Balancingrock** [comment]
By coincidence (? makes you wonder ?) I have started to port al our open source projects to Linux and iOS two days ago. As the time allotment is not very high, it might take a week or two (hopefully not more) before everything is ready.

**Comment by Balancingrock** [comment]
iOS support implemented in version 2.2.3
