### ISSUE TITLE
Warning: 'asl_log_message' is deprecated

### ISSUE THREAD

**Issue by whitehat007** [Balancingrock/SwifterLog#3]
When compiling, Xcode gives me the following error message: `'asl_log_message' is deprecated: first deprecated in macOS 10.12 - os_log(3) has replaced asl(3)`. Not a big deal, but perhaps worth following up on?

I'm running Xcode version 11.5 (11E608c) on macOS 10.15.5, and my project is compiled for macOS 10.12+.

**Comment by Balancingrock** [comment]
The latest releases of SwifterLog no longer reference the ASL log.
This is probably due to having your own fork based on an older release.
